/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    Filters: typeof import('./src/components/Filters.vue')['default']
    Flag: typeof import('./src/components/Flag.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconLucideBean: typeof import('~icons/lucide/bean')['default']
    IconLucideCookingPot: typeof import('~icons/lucide/cooking-pot')['default']
    IconLucideCroissant: typeof import('~icons/lucide/croissant')['default']
    IconLucideDessert: typeof import('~icons/lucide/dessert')['default']
    IconLucideEdit: typeof import('~icons/lucide/edit')['default']
    IconLucideEraser: typeof import('~icons/lucide/eraser')['default']
    IconLucideFilter: typeof import('~icons/lucide/filter')['default']
    IconLucideFishSymbol: typeof import('~icons/lucide/fish-symbol')['default']
    IconLucideHome: typeof import('~icons/lucide/home')['default']
    IconLucideLabCocktail: typeof import('~icons/lucide-lab/cocktail')['default']
    IconLucideLabGarlic: typeof import('~icons/lucide-lab/garlic')['default']
    IconLucideLeafyGreen: typeof import('~icons/lucide/leafy-green')['default']
    IconLucideRotateCcw: typeof import('~icons/lucide/rotate-ccw')['default']
    IconLucideSalad: typeof import('~icons/lucide/salad')['default']
    IconLucideSave: typeof import('~icons/lucide/save')['default']
    IconLucideShuffle: typeof import('~icons/lucide/shuffle')['default']
    IconLucideSoup: typeof import('~icons/lucide/soup')['default']
    IconLucideSquarePlus: typeof import('~icons/lucide/square-plus')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideSunMoon: typeof import('~icons/lucide/sun-moon')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    ImageSelector: typeof import('./src/components/ImageSelector.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Recipe: typeof import('./src/components/Recipe.vue')['default']
    RecipeCard: typeof import('./src/components/RecipeCard.vue')['default']
    RecipeEditor: typeof import('./src/components/RecipeEditor.vue')['default']
    RecipeIcons: typeof import('./src/components/RecipeIcons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TooltipIcon: typeof import('./src/components/TooltipIcon.vue')['default']
    Vulgars: typeof import('./src/components/Vulgars.vue')['default']
  }
}
