services:
  recipebook:
    image: uvmain/recipebook:latest
    container_name: recipebook
    env_file:
      - .env
    volumes:
      - /mnt/main/docker/recipebook:/data
    ports:
      - "3000:8080"