services:
  recipebook:
    image: recipebook:latest
    container_name: recipebook
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./images:/images
    ports:
      - "3001:8080"