export const countryFlags = [
  { name: 'Afghanistan', icon: 'flag:af-4x3' },
  { name: 'Åland Islands', icon: 'flag:ax-4x3' },
  { name: 'Albania', icon: 'flag:al-4x3' },
  { name: 'Algeria', icon: 'flag:dz-4x3' },
  { name: 'American Samoa', icon: 'flag:as-4x3' },
  { name: 'Andorra', icon: 'flag:ad-4x3' },
  { name: 'Angola', icon: 'flag:ao-4x3' },
  { name: 'Anguilla', icon: 'flag:ai-4x3' },
  { name: 'Antarctica', icon: 'flag:aq-4x3' },
  { name: 'Antigua and Barbuda', icon: 'flag:ag-4x3' },
  { name: 'Argentina', icon: 'flag:ar-4x3' },
  { name: 'Armenia', icon: 'flag:am-4x3' },
  { name: 'Aruba', icon: 'flag:aw-4x3' },
  { name: 'Australia', icon: 'flag:au-4x3' },
  { name: 'Austria', icon: 'flag:at-4x3' },
  { name: 'Azerbaijan', icon: 'flag:az-4x3' },
  { name: 'Bahamas', icon: 'flag:bs-4x3' },
  { name: 'Bahrain', icon: 'flag:bh-4x3' },
  { name: 'Bangladesh', icon: 'flag:bd-4x3' },
  { name: 'Barbados', icon: 'flag:bb-4x3' },
  { name: 'Belarus', icon: 'flag:by-4x3' },
  { name: 'Belgium', icon: 'flag:be-4x3' },
  { name: 'Belize', icon: 'flag:bz-4x3' },
  { name: 'Benin', icon: 'flag:bj-4x3' },
  { name: 'Bermuda', icon: 'flag:bm-4x3' },
  { name: 'Bhutan', icon: 'flag:bt-4x3' },
  { name: 'Bolivia', icon: 'flag:bo-4x3' },
  { name: 'Bosnia and Herzegovina', icon: 'flag:ba-4x3' },
  { name: 'Botswana', icon: 'flag:bw-4x3' },
  { name: 'Bouvet Island', icon: 'flag:bv-4x3' },
  { name: 'Brazil', icon: 'flag:br-4x3' },
  { name: 'British Indian Ocean Territory', icon: 'flag:io-4x3' },
  { name: 'Brunei Darussalam', icon: 'flag:bn-4x3' },
  { name: 'Bulgaria', icon: 'flag:bg-4x3' },
  { name: 'Burkina Faso', icon: 'flag:bf-4x3' },
  { name: 'Burundi', icon: 'flag:bi-4x3' },
  { name: 'Cambodia', icon: 'flag:kh-4x3' },
  { name: 'Cameroon', icon: 'flag:cm-4x3' },
  { name: 'Canada', icon: 'flag:ca-4x3' },
  { name: 'Cape Verde', icon: 'flag:cv-4x3' },
  { name: 'Cayman Islands', icon: 'flag:ky-4x3' },
  { name: 'Central African Republic', icon: 'flag:cf-4x3' },
  { name: 'Chad', icon: 'flag:td-4x3' },
  { name: 'Chile', icon: 'flag:cl-4x3' },
  { name: 'China', icon: 'flag:cn-4x3' },
  { name: 'Christmas Island', icon: 'flag:cx-4x3' },
  { name: 'Cocos (Keeling) Islands', icon: 'flag:cc-4x3' },
  { name: 'Colombia', icon: 'flag:co-4x3' },
  { name: 'Comoros', icon: 'flag:km-4x3' },
  { name: 'Congo', icon: 'flag:cg-4x3' },
  { name: 'Congo, The Democratic Republic of the', icon: 'flag:cd-4x3' },
  { name: 'Cook Islands', icon: 'flag:ck-4x3' },
  { name: 'Costa Rica', icon: 'flag:cr-4x3' },
  { name: 'Cote D\'Ivoire', icon: 'flag:ci-4x3' },
  { name: 'Croatia', icon: 'flag:hr-4x3' },
  { name: 'Cuba', icon: 'flag:cu-4x3' },
  { name: 'Cyprus', icon: 'flag:cy-4x3' },
  { name: 'Czech Republic', icon: 'flag:cz-4x3' },
  { name: 'Denmark', icon: 'flag:dk-4x3' },
  { name: 'Djibouti', icon: 'flag:dj-4x3' },
  { name: 'Dominica', icon: 'flag:dm-4x3' },
  { name: 'Dominican Republic', icon: 'flag:do-4x3' },
  { name: 'Ecuador', icon: 'flag:ec-4x3' },
  { name: 'Egypt', icon: 'flag:eg-4x3' },
  { name: 'El Salvador', icon: 'flag:sv-4x3' },
  { name: 'Equatorial Guinea', icon: 'flag:gq-4x3' },
  { name: 'Eritrea', icon: 'flag:er-4x3' },
  { name: 'Estonia', icon: 'flag:ee-4x3' },
  { name: 'Ethiopia', icon: 'flag:et-4x3' },
  { name: 'Falkland Islands', icon: 'flag:fk-4x3' },
  { name: 'Faroe Islands', icon: 'flag:fo-4x3' },
  { name: 'Fiji', icon: 'flag:fj-4x3' },
  { name: 'Finland', icon: 'flag:fi-4x3' },
  { name: 'France', icon: 'flag:fr-4x3' },
  { name: 'French Guiana', icon: 'flag:gf-4x3' },
  { name: 'French Polynesia', icon: 'flag:pf-4x3' },
  { name: 'French Southern Territories', icon: 'flag:tf-4x3' },
  { name: 'Gabon', icon: 'flag:ga-4x3' },
  { name: 'Gambia', icon: 'flag:gm-4x3' },
  { name: 'Georgia', icon: 'flag:ge-4x3' },
  { name: 'Germany', icon: 'flag:de-4x3' },
  { name: 'Ghana', icon: 'flag:gh-4x3' },
  { name: 'Gibraltar', icon: 'flag:gi-4x3' },
  { name: 'Greece', icon: 'flag:gr-4x3' },
  { name: 'Greenland', icon: 'flag:gl-4x3' },
  { name: 'Grenada', icon: 'flag:gd-4x3' },
  { name: 'Guadeloupe', icon: 'flag:gp-4x3' },
  { name: 'Guatemala', icon: 'flag:gt-4x3' },
  { name: 'Guernsey', icon: 'flag:gg-4x3' },
  { name: 'Guinea', icon: 'flag:gn-4x3' },
  { name: 'Guinea-Bissau', icon: 'flag:gw-4x3' },
  { name: 'Guyana', icon: 'flag:gy-4x3' },
  { name: 'Haiti', icon: 'flag:ht-4x3' },
  { name: 'Heard Island and Mcdonald Islands', icon: 'flag:hm-4x3' },
  { name: 'Holy See (Vatican City State)', icon: 'flag:va-4x3' },
  { name: 'Honduras', icon: 'flag:hn-4x3' },
  { name: 'Hong Kong', icon: 'flag:hk-4x3' },
  { name: 'Hungary', icon: 'flag:hu-4x3' },
  { name: 'Iceland', icon: 'flag:is-4x3' },
  { name: 'India', icon: 'flag:in-4x3' },
  { name: 'Indonesia', icon: 'flag:id-4x3' },
  { name: 'Iran', icon: 'flag:ir-4x3' },
  { name: 'Iraq', icon: 'flag:iq-4x3' },
  { name: 'Ireland', icon: 'flag:ie-4x3' },
  { name: 'Isle of Man', icon: 'flag:im-4x3' },
  { name: 'Israel', icon: 'flag:il-4x3' },
  { name: 'Italy', icon: 'flag:it-4x3' },
  { name: 'Jamaica', icon: 'flag:jm-4x3' },
  { name: 'Japan', icon: 'flag:jp-4x3' },
  { name: 'Jersey', icon: 'flag:je-4x3' },
  { name: 'Jordan', icon: 'flag:jo-4x3' },
  { name: 'Kazakhstan', icon: 'flag:kz-4x3' },
  { name: 'Kenya', icon: 'flag:ke-4x3' },
  { name: 'Kiribati', icon: 'flag:ki-4x3' },
  { name: 'North Korea', icon: 'flag:kp-4x3' },
  { name: 'South Korea', icon: 'flag:kr-4x3' },
  { name: 'Kuwait', icon: 'flag:kw-4x3' },
  { name: 'Kyrgyzstan', icon: 'flag:kg-4x3' },
  { name: 'Lao', icon: 'flag:la-4x3' },
  { name: 'Latvia', icon: 'flag:lv-4x3' },
  { name: 'Lebanon', icon: 'flag:lb-4x3' },
  { name: 'Lesotho', icon: 'flag:ls-4x3' },
  { name: 'Liberia', icon: 'flag:lr-4x3' },
  { name: 'Libya', icon: 'flag:ly-4x3' },
  { name: 'Liechtenstein', icon: 'flag:li-4x3' },
  { name: 'Lithuania', icon: 'flag:lt-4x3' },
  { name: 'Luxembourg', icon: 'flag:lu-4x3' },
  { name: 'Macao', icon: 'flag:mo-4x3' },
  { name: 'Macedonia', icon: 'flag:mk-4x3' },
  { name: 'Madagascar', icon: 'flag:mg-4x3' },
  { name: 'Malawi', icon: 'flag:mw-4x3' },
  { name: 'Malaysia', icon: 'flag:my-4x3' },
  { name: 'Maldives', icon: 'flag:mv-4x3' },
  { name: 'Mali', icon: 'flag:ml-4x3' },
  { name: 'Malta', icon: 'flag:mt-4x3' },
  { name: 'Marshall Islands', icon: 'flag:mh-4x3' },
  { name: 'Martinique', icon: 'flag:mq-4x3' },
  { name: 'Mauritania', icon: 'flag:mr-4x3' },
  { name: 'Mauritius', icon: 'flag:mu-4x3' },
  { name: 'Mayotte', icon: 'flag:yt-4x3' },
  { name: 'Mexico', icon: 'flag:mx-4x3' },
  { name: 'Micronesia', icon: 'flag:fm-4x3' },
  { name: 'Moldova', icon: 'flag:md-4x3' },
  { name: 'Monaco', icon: 'flag:mc-4x3' },
  { name: 'Mongolia', icon: 'flag:mn-4x3' },
  { name: 'Montserrat', icon: 'flag:ms-4x3' },
  { name: 'Morocco', icon: 'flag:ma-4x3' },
  { name: 'Mozambique', icon: 'flag:mz-4x3' },
  { name: 'Myanmar', icon: 'flag:mm-4x3' },
  { name: 'Namibia', icon: 'flag:na-4x3' },
  { name: 'Nauru', icon: 'flag:nr-4x3' },
  { name: 'Nepal', icon: 'flag:np-4x3' },
  { name: 'Netherlands', icon: 'flag:nl-4x3' },
  { name: 'New Caledonia', icon: 'flag:nc-4x3' },
  { name: 'New Zealand', icon: 'flag:nz-4x3' },
  { name: 'Nicaragua', icon: 'flag:ni-4x3' },
  { name: 'Niger', icon: 'flag:ne-4x3' },
  { name: 'Nigeria', icon: 'flag:ng-4x3' },
  { name: 'Niue', icon: 'flag:nu-4x3' },
  { name: 'Norfolk Island', icon: 'flag:nf-4x3' },
  { name: 'Northern Mariana Islands', icon: 'flag:mp-4x3' },
  { name: 'Norway', icon: 'flag:no-4x3' },
  { name: 'Oman', icon: 'flag:om-4x3' },
  { name: 'Pakistan', icon: 'flag:pk-4x3' },
  { name: 'Palau', icon: 'flag:pw-4x3' },
  { name: 'Palestine', icon: 'flag:ps-4x3' },
  { name: 'Panama', icon: 'flag:pa-4x3' },
  { name: 'Papua New Guinea', icon: 'flag:pg-4x3' },
  { name: 'Paraguay', icon: 'flag:py-4x3' },
  { name: 'Peru', icon: 'flag:pe-4x3' },
  { name: 'Philippines', icon: 'flag:ph-4x3' },
  { name: 'Pitcairn', icon: 'flag:pn-4x3' },
  { name: 'Poland', icon: 'flag:pl-4x3' },
  { name: 'Portugal', icon: 'flag:pt-4x3' },
  { name: 'Puerto Rico', icon: 'flag:pr-4x3' },
  { name: 'Qatar', icon: 'flag:qa-4x3' },
  { name: 'Reunion', icon: 'flag:re-4x3' },
  { name: 'Romania', icon: 'flag:ro-4x3' },
  { name: 'Russia', icon: 'flag:ru-4x3' },
  { name: 'Rwanda', icon: 'flag:rw-4x3' },
  { name: 'Saint Helena', icon: 'flag:sh-4x3' },
  { name: 'Saint Kitts and Nevis', icon: 'flag:kn-4x3' },
  { name: 'Saint Lucia', icon: 'flag:lc-4x3' },
  { name: 'Saint Pierre and Miquelon', icon: 'flag:pm-4x3' },
  { name: 'Saint Vincent and the Grenadines', icon: 'flag:vc-4x3' },
  { name: 'Samoa', icon: 'flag:ws-4x3' },
  { name: 'San Marino', icon: 'flag:sm-4x3' },
  { name: 'Sao Tome and Principe', icon: 'flag:st-4x3' },
  { name: 'Saudi Arabia', icon: 'flag:sa-4x3' },
  { name: 'Senegal', icon: 'flag:sn-4x3' },
  { name: 'Seychelles', icon: 'flag:sc-4x3' },
  { name: 'Sierra Leone', icon: 'flag:sl-4x3' },
  { name: 'Singapore', icon: 'flag:sg-4x3' },
  { name: 'Slovakia', icon: 'flag:sk-4x3' },
  { name: 'Slovenia', icon: 'flag:si-4x3' },
  { name: 'Solomon Islands', icon: 'flag:sb-4x3' },
  { name: 'Somalia', icon: 'flag:so-4x3' },
  { name: 'South Africa', icon: 'flag:za-4x3' },
  { name: 'South Georgia and the South Sandwich Islands', icon: 'flag:gs-4x3' },
  { name: 'Spain', icon: 'flag:es-4x3' },
  { name: 'Sri Lanka', icon: 'flag:lk-4x3' },
  { name: 'Sudan', icon: 'flag:sd-4x3' },
  { name: 'Suriname', icon: 'flag:sr-4x3' },
  { name: 'Svalbard and Jan Mayen', icon: 'flag:sj-4x3' },
  { name: 'Swaziland', icon: 'flag:sz-4x3' },
  { name: 'Sweden', icon: 'flag:se-4x3' },
  { name: 'Switzerland', icon: 'flag:ch-4x3' },
  { name: 'Syrian Arab Republic', icon: 'flag:sy-4x3' },
  { name: 'Taiwan, Province of China', icon: 'flag:tw-4x3' },
  { name: 'Tajikistan', icon: 'flag:tj-4x3' },
  { name: 'Tanzania', icon: 'flag:tz-4x3' },
  { name: 'Thailand', icon: 'flag:th-4x3' },
  { name: 'Timor-Leste', icon: 'flag:tl-4x3' },
  { name: 'Togo', icon: 'flag:tg-4x3' },
  { name: 'Tokelau', icon: 'flag:tk-4x3' },
  { name: 'Tonga', icon: 'flag:to-4x3' },
  { name: 'Trinidad and Tobago', icon: 'flag:tt-4x3' },
  { name: 'Tunisia', icon: 'flag:tn-4x3' },
  { name: 'Turkey', icon: 'flag:tr-4x3' },
  { name: 'Turkmenistan', icon: 'flag:tm-4x3' },
  { name: 'Turks and Caicos Islands', icon: 'flag:tc-4x3' },
  { name: 'Tuvalu', icon: 'flag:tv-4x3' },
  { name: 'Uganda', icon: 'flag:ug-4x3' },
  { name: 'Ukraine', icon: 'flag:ua-4x3' },
  { name: 'United Arab Emirates', icon: 'flag:ae-4x3' },
  { name: 'United Kingdom', icon: 'flag:gb-4x3' },
  { name: 'United States', icon: 'flag:us-4x3' },
  { name: 'Uruguay', icon: 'flag:uy-4x3' },
  { name: 'Uzbekistan', icon: 'flag:uz-4x3' },
  { name: 'Vanuatu', icon: 'flag:vu-4x3' },
  { name: 'Venezuela', icon: 'flag:ve-4x3' },
  { name: 'Vietnam', icon: 'flag:vn-4x3' },
  { name: 'Virgin Islands, British', icon: 'flag:vg-4x3' },
  { name: 'Virgin Islands, U.S.', icon: 'flag:vi-4x3' },
  { name: 'Wallis and Futuna', icon: 'flag:wf-4x3' },
  { name: 'Western Sahara', icon: 'flag:eh-4x3' },
  { name: 'Yemen', icon: 'flag:ye-4x3' },
  { name: 'Zambia', icon: 'flag:zm-4x3' },
  { name: 'Zimbabwe', icon: 'flag:zw-4x3' },
]
